package:
  name: r-scplotter
  version: 0.3.0

source:
  path: ..

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-callr
    - r-circlize
    - r-clustree
    - r-concaveman
    - r-dplyr
    - r-ggalluvial
    - r-ggforce
    - r-ggnewscale
    - r-ggplot2
    - r-ggpubr
    - r-ggraph
    - r-ggridges
    - r-ggupset
    - r-ggvenndiagram
    - r-ggwordcloud
    - r-gridgraphics
    - r-hexbin
    - r-metap
    - r-igraph
    - r-inext
    - r-r6
    - r-rlang
    - r-scales
    - r-scattermore
    - r-seurat
    - r-seuratobject
    - r-stringr
    - r-tidyr
    - bioconda::bioconductor-complexheatmap
    - pwwang::r-gglogger
    - pwwang::r-plotthis
    - pwwang::r-tidyprompt
    - pwwang::bioconductor-screpertoire

  run:
    - r-base
    - r-callr
    - r-circlize
    - r-clustree
    - r-concaveman
    - r-dplyr
    - r-ggalluvial
    - r-ggforce
    - r-ggnewscale
    - r-ggplot2
    - r-ggpubr
    - r-ggraph
    - r-ggridges
    - r-ggupset
    - r-ggvenndiagram
    - r-ggwordcloud
    - r-gridgraphics
    - r-hexbin
    - r-metap
    - r-igraph
    - r-inext
    - r-r6
    - r-rlang
    - r-scales
    - r-scattermore
    - r-seurat
    - r-seuratobject
    - r-stringr
    - r-tidyr
    - bioconda::bioconductor-complexheatmap
    - pwwang::r-gglogger
    - pwwang::r-plotthis
    - pwwang::r-tidyprompt
    - pwwang::bioconductor-screpertoire

test:
  commands:
    - $R -e "library('scplotter')"

about:
  home: https://github.com/pwwang/scplotter
  license: GPL-3
  summary: provides a set of functions to visualize single-cell sequencing data in an easy and efficient way.
  license_family: GPL
  license_file: LICENSE.md
